spring:
  application:
    name: Athenea
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/athenea
    username: atheneadba
    password: athenea


  jpa:
    database: MYSQL
    hibernate.ddl-auto: create-drop
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

  servlet:
    multipart:
      max-file-size: 200MB
      enabled: true
      file-size-threshold: 2KB
      max-request-size: 215MB



server:
  port: 8898
  error:
    whitelabel:
      enabled: false
  address: 127.0.0.1

logging:
  level:
    root: WARN
    org.springframework.web: INFO
    org.springframework.security: INFO
    com.bt: INFO

security:
  jwt:
    token:
      secret-key: my$ecret
      expire-length: 86400 # 24h * 60 min * 60 sec
      extended-expire-length: 604800 # 7h * 24h * 60 min * 60 sec
